---

service:
  metric_name: ssp_balance
  messages:
    init: -1000000
    disabled: -1000001
    no_answer: -1000002
    captcha: -1000003
    cannot_proceed: -1000004
    rate_limit: -1000005
    parsing_error: -1000006
    connection_error: -1000007
  user_agents:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33
    - Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
    - Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
    - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
    - Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
    - Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
identifiers:
  AlmatelRussia:
    - identifier: identifier_almatel
      password: password_almatel
      labels:
        description: Almatel Description
        currency: ₽
        category: SP
      tls_verify: false
      poll_interval: 1800
  ArubaCloud:
    - identifier: identifier_arubacloud
      password: password_arubacloud
      labels:
        description: ArubaCloud Description
        currency: €
        category: Hosting
      poll_interval: 1800
  MegafonRussiaB2C:
    - identifier: identifier_megafon
      password: password_megafon
      labels:
        category: SP
        currency: ₽
        description: Megafon Description
      poll_interval: 1800
      disabled: false
  Vultr:
    - identifier: identifier_vultr
      password: apikey_vultr
      labels:
        description: Vultr Description
        currency: $
        category: Hosting
      poll_interval: 1800
  WifireRussia:
    - identifier: identifier_wifire
      password: password_wifire
      labels:
        description: Wifire Description
        currency: ₽
        category: SP
      poll_interval: 1800
      disabled: true